# Generated by Django 4.1.5 on 2023-01-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'MyForm',
                'verbose_name_plural': 'MyForms',
            },
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('text', models.TextField(verbose_name='text')),
                ('date', models.DateField(verbose_name='date')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions_form.myform')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
            },
        ),
    ]
